default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 15
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 123 %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

development:
  <<: *default
  database: <%= File.open("#{Rails.root}/.database").read.strip rescue "job_api_development" %>

test:
  <<: *default
  database: job_api_test

production:
  <<: *default
  database: job_api_production
